export const UNIT_TYPES = {
  length:{label:'Length',defaultTarget:'km',units:{mm:{label:'mm',aliases:['mm','millimeter','millimeters','millimetre','millimetres'],factor:.001},cm:{label:'cm',aliases:['cm','centimeter','centimeters','centimetre','centimetres'],factor:.01},m:{label:'m',aliases:['m','meter','meters','metre','metres'],factor:1},km:{label:'km',aliases:['km','kilometer','kilometers','kilometre','kilometres'],factor:1000},in:{label:'in',aliases:['in','inch','inches'],factor:.0254},ft:{label:'ft',aliases:['ft','foot','feet'],factor:.3048},yd:{label:'yd',aliases:['yd','yard','yards'],factor:.9144},mi:{label:'mi',aliases:['mi','mile','miles'],factor:1609.344}}},
  weight:{label:'Weight',defaultTarget:'kg',units:{mg:{label:'mg',aliases:['mg','milligram','milligrams'],factor:.000001},g:{label:'g',aliases:['g','gram','grams'],factor:.001},kg:{label:'kg',aliases:['kg','kilogram','kilograms','kilo','kilos'],factor:1},oz:{label:'oz',aliases:['oz','ounce','ounces'],factor:.028349523125},lb:{label:'lb',aliases:['lb','lbs','pound','pounds'],factor:.45359237},ton:{label:'ton',aliases:['ton','tons','tonne','tonnes'],factor:1000}}},
  temperature:{label:'Temperature',defaultTarget:'°C',units:{'°C':{label:'°C',aliases:['°c','c','celsius','centigrade']},'°F':{label:'°F',aliases:['°f','f','fahrenheit']},K:{label:'K',aliases:['k','kelvin','kelvins']}}},
  data:{label:'Data',defaultTarget:'MB',units:{bit:{label:'bit',aliases:['bit','bits'],bytes:.125},Byte:{label:'Byte',aliases:['byte','bytes','b'],bytes:1},KB:{label:'KB',aliases:['kb','kilobyte','kilobytes'],bytes:1000},MB:{label:'MB',aliases:['mb','megabyte','megabytes'],bytes:1000000},GB:{label:'GB',aliases:['gb','gigabyte','gigabytes'],bytes:1000000000},TB:{label:'TB',aliases:['tb','terabyte','terabytes'],bytes:1000000000000}}}
};
const ALIAS_INDEX=new Map(); for(const [type,config] of Object.entries(UNIT_TYPES)){for(const [code,unit] of Object.entries(config.units)){for(const alias of unit.aliases) ALIAS_INDEX.set(alias.toLowerCase(),{type,unit:code});}}
export const resolveUnit=(alias)=>ALIAS_INDEX.get(String(alias).trim().toLowerCase())||null;
export const getDefaultTarget=(type)=>UNIT_TYPES[type]?.defaultTarget||null;
export const getUnitLabel=(type,unit)=>UNIT_TYPES[type]?.units?.[unit]?.label||unit;
